# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Gnolangci-lint"
description: "Official golangci-lint action with line-attached annotations for found issues, caching and parallel execution."
author: "teritori"
inputs:
  version:
    description: |
      The commit hash or tag to use from https://github.com/gnolang/gno
    required: false
  working-directory:
    description: "golangci-lint working directory, default is project root"
    required: false
  github-token:
    description: "the token is used for fetching patch of a pull request to show only new issues"
    default: ${{ github.token }}
    required: false
  only-new-issues:
    description: "if set to true and the action runs on a pull request - the action outputs only newly found issues"
    default: 'false'
    required: false
  skip-cache:
    description: |
      if set to true then the all caching functionality will be complete disabled,
      takes precedence over all other caching options.
    default: 'false'
    required: false
  skip-save-cache:
    description: |
      if set to true then the action will not save any caches, but it may still
      restore existing caches, subject to other options.
    default: 'false'
    required: false
  problem-matchers:
    description: "Force the usage of the embedded problem matchers"
    default: 'false'
    required: false
  args:
    description: "golangci-lint command line arguments"
    default: ""
    required: false
  cache-invalidation-interval:
    description: "Periodically invalidate a cache because a new code being added. (number of days)"
    default: '7'
    required: false
runs:
  using: "node20"
  main: "dist/run/index.js"
  post: "dist/post_run/index.js"
branding:
  icon: "shield"
  color: "white"
